/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransportationRouteImport } from './routes/transportation'
import { Route as SustainabilityRouteImport } from './routes/sustainability'
import { Route as StadiumRouteImport } from './routes/stadium'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as OperationsRouteImport } from './routes/operations'
import { Route as NavigationRouteImport } from './routes/navigation'
import { Route as InsightsRouteImport } from './routes/insights'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as AssistantRouteImport } from './routes/assistant'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiInsightsRouteImport } from './routes/api/insights'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const TransportationRoute = TransportationRouteImport.update({
  id: '/transportation',
  path: '/transportation',
  getParentRoute: () => rootRouteImport,
} as any)
const SustainabilityRoute = SustainabilityRouteImport.update({
  id: '/sustainability',
  path: '/sustainability',
  getParentRoute: () => rootRouteImport,
} as any)
const StadiumRoute = StadiumRouteImport.update({
  id: '/stadium',
  path: '/stadium',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const OperationsRoute = OperationsRouteImport.update({
  id: '/operations',
  path: '/operations',
  getParentRoute: () => rootRouteImport,
} as any)
const NavigationRoute = NavigationRouteImport.update({
  id: '/navigation',
  path: '/navigation',
  getParentRoute: () => rootRouteImport,
} as any)
const InsightsRoute = InsightsRouteImport.update({
  id: '/insights',
  path: '/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantRoute = AssistantRouteImport.update({
  id: '/assistant',
  path: '/assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInsightsRoute = ApiInsightsRouteImport.update({
  id: '/api/insights',
  path: '/api/insights',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/assistant': typeof AssistantRoute
  '/emergency': typeof EmergencyRoute
  '/insights': typeof InsightsRoute
  '/navigation': typeof NavigationRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stadium': typeof StadiumRoute
  '/sustainability': typeof SustainabilityRoute
  '/transportation': typeof TransportationRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insights': typeof ApiInsightsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/assistant': typeof AssistantRoute
  '/emergency': typeof EmergencyRoute
  '/insights': typeof InsightsRoute
  '/navigation': typeof NavigationRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stadium': typeof StadiumRoute
  '/sustainability': typeof SustainabilityRoute
  '/transportation': typeof TransportationRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insights': typeof ApiInsightsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/assistant': typeof AssistantRoute
  '/emergency': typeof EmergencyRoute
  '/insights': typeof InsightsRoute
  '/navigation': typeof NavigationRoute
  '/operations': typeof OperationsRoute
  '/reports': typeof ReportsRoute
  '/settings': typeof SettingsRoute
  '/stadium': typeof StadiumRoute
  '/sustainability': typeof SustainabilityRoute
  '/transportation': typeof TransportationRoute
  '/api/chat': typeof ApiChatRoute
  '/api/insights': typeof ApiInsightsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/assistant'
    | '/emergency'
    | '/insights'
    | '/navigation'
    | '/operations'
    | '/reports'
    | '/settings'
    | '/stadium'
    | '/sustainability'
    | '/transportation'
    | '/api/chat'
    | '/api/insights'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/assistant'
    | '/emergency'
    | '/insights'
    | '/navigation'
    | '/operations'
    | '/reports'
    | '/settings'
    | '/stadium'
    | '/sustainability'
    | '/transportation'
    | '/api/chat'
    | '/api/insights'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/assistant'
    | '/emergency'
    | '/insights'
    | '/navigation'
    | '/operations'
    | '/reports'
    | '/settings'
    | '/stadium'
    | '/sustainability'
    | '/transportation'
    | '/api/chat'
    | '/api/insights'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AssistantRoute: typeof AssistantRoute
  EmergencyRoute: typeof EmergencyRoute
  InsightsRoute: typeof InsightsRoute
  NavigationRoute: typeof NavigationRoute
  OperationsRoute: typeof OperationsRoute
  ReportsRoute: typeof ReportsRoute
  SettingsRoute: typeof SettingsRoute
  StadiumRoute: typeof StadiumRoute
  SustainabilityRoute: typeof SustainabilityRoute
  TransportationRoute: typeof TransportationRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiInsightsRoute: typeof ApiInsightsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transportation': {
      id: '/transportation'
      path: '/transportation'
      fullPath: '/transportation'
      preLoaderRoute: typeof TransportationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sustainability': {
      id: '/sustainability'
      path: '/sustainability'
      fullPath: '/sustainability'
      preLoaderRoute: typeof SustainabilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/stadium': {
      id: '/stadium'
      path: '/stadium'
      fullPath: '/stadium'
      preLoaderRoute: typeof StadiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/operations': {
      id: '/operations'
      path: '/operations'
      fullPath: '/operations'
      preLoaderRoute: typeof OperationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/navigation': {
      id: '/navigation'
      path: '/navigation'
      fullPath: '/navigation'
      preLoaderRoute: typeof NavigationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insights': {
      id: '/insights'
      path: '/insights'
      fullPath: '/insights'
      preLoaderRoute: typeof InsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant': {
      id: '/assistant'
      path: '/assistant'
      fullPath: '/assistant'
      preLoaderRoute: typeof AssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/insights': {
      id: '/api/insights'
      path: '/api/insights'
      fullPath: '/api/insights'
      preLoaderRoute: typeof ApiInsightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AssistantRoute: AssistantRoute,
  EmergencyRoute: EmergencyRoute,
  InsightsRoute: InsightsRoute,
  NavigationRoute: NavigationRoute,
  OperationsRoute: OperationsRoute,
  ReportsRoute: ReportsRoute,
  SettingsRoute: SettingsRoute,
  StadiumRoute: StadiumRoute,
  SustainabilityRoute: SustainabilityRoute,
  TransportationRoute: TransportationRoute,
  ApiChatRoute: ApiChatRoute,
  ApiInsightsRoute: ApiInsightsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
